
package com.steven.cxf.client;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "CXFWervice", targetNamespace = "http://cxf.steven.com/", wsdlLocation = "http://127.0.0.1:8888/hello?WSDL")
public class CXFWervice_Service
    extends Service
{

    private final static URL CXFWERVICE_WSDL_LOCATION;
    private final static WebServiceException CXFWERVICE_EXCEPTION;
    private final static QName CXFWERVICE_QNAME = new QName("http://cxf.steven.com/", "CXFWervice");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://127.0.0.1:8888/hello?WSDL");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        CXFWERVICE_WSDL_LOCATION = url;
        CXFWERVICE_EXCEPTION = e;
    }

    public CXFWervice_Service() {
        super(__getWsdlLocation(), CXFWERVICE_QNAME);
    }

    public CXFWervice_Service(WebServiceFeature... features) {
        super(__getWsdlLocation(), CXFWERVICE_QNAME, features);
    }

    public CXFWervice_Service(URL wsdlLocation) {
        super(wsdlLocation, CXFWERVICE_QNAME);
    }

    public CXFWervice_Service(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, CXFWERVICE_QNAME, features);
    }

    public CXFWervice_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public CXFWervice_Service(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns CXFWervice
     */
    @WebEndpoint(name = "CXFWervicePort")
    public CXFWervice getCXFWervicePort() {
        return super.getPort(new QName("http://cxf.steven.com/", "CXFWervicePort"), CXFWervice.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns CXFWervice
     */
    @WebEndpoint(name = "CXFWervicePort")
    public CXFWervice getCXFWervicePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://cxf.steven.com/", "CXFWervicePort"), CXFWervice.class, features);
    }

    private static URL __getWsdlLocation() {
        if (CXFWERVICE_EXCEPTION!= null) {
            throw CXFWERVICE_EXCEPTION;
        }
        return CXFWERVICE_WSDL_LOCATION;
    }

}
